### ISSUE TITLE
Problem with the saunabox device after adding it to the homekit

### ISSUE THREAD

**Issue by cmeliak** [Piotr-Grochowski/eu.blebox#1]
I want to ask if there is any way to repair the device in homekit. After adding the saunabox to the homey and then to the homekit, I can set the maximum temperature to 38 degrees in the homekit, but in the homey I can set the temperature up to 105 degrees.

**Comment by Piotr-Grochowski** [comment]
Hello,
There is no such limitation in the BleBox app. Maybe it's something with the HomeKit integration. How to you expose devices to HomeKit? Via built-in experiment (the worst in my opinion), via HomeyKit app (I use it but it has some minor problems) or HomeKitty app (the newest app, total rewrite of HomeyKit, I didn't try that yet but it has many good opinions)?
