### ISSUE TITLE
[Feature Request] Adding action cards with effects

### ISSUE THREAD

**Issue by dirkg173** [Piotr-Grochowski/eu.blebox#10]
Hi Piotr,
I think I asked about it in the forum a long time ago.
Is it possible to add action cards (Then...) with effects (dimming, strobe and bell effect), as it's possible with the wLightBoxS in the original BleBox smartphone app, for example?

Br,
Dirk

**Comment by Piotr-Grochowski** [comment]
I've already done it with pixelBox and full rgbw wlightBox. wlightBoxS is next on the TODO list.

**Comment by dirkg173** [comment]
Great, many thanks!

**Comment by Piotr-Grochowski** [comment]
The effects have been added. Now available in the test version, as soon as Athom approves the new version, it will also be available as a stable version.
