### ISSUE TITLE
[Bug] Trigger flow card "(   ) state changed." doesn't work

### ISSUE THREAD

**Issue by dirkg173** [Piotr-Grochowski/eu.blebox#11]
Hi Piotr,
just found out, that there is a general trigger flow card (And...) available, named "(   ) state changed.".
It seems, that this card doesn't work.
If I use this flow card and want to choose a device via drop down list, none device is listed (please see screenshot).
However, I have to mention that I only have the wLightBoxS in use, with which this flow card should probably work (State changed = On/Off?).
Or is this card intended for other state changes?

Br,
Dirk

<img width="310" alt="SCR-20240104-mazp" src="https://github.com/Piotr-Grochowski/eu.blebox/assets/40319629/ff18b8f0-57a3-4a4f-8f9d-86cf8095afaa">

**Comment by Piotr-Grochowski** [comment]
There is one word missing, I'll correct this in next version.
Should be: Thermostat [[device]] state changed.
It's for thermoBox, saunaBox, etc.
