### ISSUE TITLE
Adding of the rainsensor to Homey

### ISSUE THREAD

**Issue by PauloHomey** [Piotr-Grochowski/eu.blebox#13]
Hello. 

One question please. 
I ordered and received the rain sensor from eshop. 
This sensor is already added to the BleBox app, but I am not able to add this sensor to my Homey Pro on the regular way. 
could you help me please with some recommendation?

thx 
Paulo

**Comment by PauloHomey** [comment]
Hi. I have added the rain sensor into the Honey, but….
Since I simulated the first time the water, 2-3 drops of water ftom the glass on the sensor (received alert) and then have wished the water from the sensor, the alert is still switching (already 2 days) between No water alarm, Yes water alarm, No water alarm,….. Already 2 days still!
Could you help me? 
Firmware is up to date. 


![IMG_7527](https://github.com/Piotr-Grochowski/eu.blebox/assets/175026022/6fae4486-29a6-45e5-8192-ee466c77d30a)
![IMG_7526](https://github.com/Piotr-Grochowski/eu.blebox/assets/175026022/1aa7ba36-3e00-4af2-9884-b10477fa337a)
![IMG_7528](https://github.com/Piotr-Grochowski/eu.blebox/assets/175026022/05c31b72-3039-4cfd-ac75-726d8003e54a)

**Comment by Piotr-Grochowski** [comment]
Please send me a diagnostic report from homey.

Pozdrawiam,
Piotr Grochowski
________________________________
Od: PauloHomey ***@***.***>
Wysłane: Wednesday, July 10, 2024 7:26:20 AM
Do: Piotr-Grochowski/eu.blebox ***@***.***>
DW: Subscribed ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Hi. I have added the rain sensor into the Honey, but….
Since I simulated the first time the water, 2-3 drops of water ftom the glass on the sensor (received alert) and then have wished the water from the sensor, the alert is still switching (already 2 days) between No water alarm, Yes water alarm, No water alarm,….. Already 2 days still!
Could you help me?
Firmware is up to date.

IMG_7527.png (view on web)<https://github.com/Piotr-Grochowski/eu.blebox/assets/175026022/6fae4486-29a6-45e5-8192-ee466c77d30a>
IMG_7526.png (view on web)<https://github.com/Piotr-Grochowski/eu.blebox/assets/175026022/1aa7ba36-3e00-4af2-9884-b10477fa337a>
IMG_7528.png (view on web)<https://github.com/Piotr-Grochowski/eu.blebox/assets/175026022/05c31b72-3039-4cfd-ac75-726d8003e54a>

**Comment by PauloHomey** [comment]
Hi Piotr. 
Thx a lot. Here you are welcome 722B2267. 
Robert

**Comment by Piotr-Grochowski** [comment]
I don’t see any diagnostic report sent from Homey App. What is this number?

Pozdrawiam,
Piotr Grochowski
________________________________
Od: PauloHomey ***@***.***>
Wysłane: Wednesday, July 10, 2024 8:07:13 AM
Do: Piotr-Grochowski/eu.blebox ***@***.***>
DW: Piotr Grochowski ***@***.***>; Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Hi Piotr.
Thx a lot. Here you are welcome 722B2267.
Robert

**Comment by PauloHomey** [comment]
Sorry, but this is regular way in Homey. 
Here the new one C2E1F4DA. Could you find it now?

![IMG_7530](https://github.com/Piotr-Grochowski/eu.blebox/assets/175026022/e07bfe5f-a9f6-4526-901b-2ac3319fa83c)

**Comment by Piotr-Grochowski** [comment]
I meant BleBox Homey App, not the Homey App itself. :)

Pozdrawiam,
Piotr Grochowski
________________________________
Od: PauloHomey ***@***.***>
Wysłane: Wednesday, July 10, 2024 9:17:25 AM
Do: Piotr-Grochowski/eu.blebox ***@***.***>
DW: Piotr Grochowski ***@***.***>; Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Sorry, but this is regular way in Homey.
Here the new one C2E1F4DA. Could you find it now?

IMG_7530.png (view on web)<https://github.com/Piotr-Grochowski/eu.blebox/assets/175026022/e07bfe5f-a9f6-4526-901b-2ac3319fa83c>

**Comment by PauloHomey** [comment]
Oh, but now understood. 😉 
8e5228c9-72aa-445b-b8ac-622be5923e4b

**Comment by PauloHomey** [comment]
Hi Pioter. 

Now is it permanently displaying YES Water Alarm, and only red flashing this icon. No more changing from No to Yes. Piotr what is the sense of this warning? When should be triggered this warning? In case of the starting rain and stopped when is rain over? Because the sensor was no more 4 days outdoor, was in the room. 
Thx. 
Robert

**Comment by PauloHomey** [comment]
Hi Piotr. 

Something new for me about rain sensor? Status still the same: Water alarm signalizing during the powered sensor in the office on the table ;).
Thx a lot.

**Comment by Piotr-Grochowski** [comment]
Hi,
I’m on vacation, so I’m not able to take care of this issue right now.


Pozdrawiam,

Piotr Grochowski

www.vmp.com.pl<http://www.vmp.com.pl/> | ***@***.******@***.***> | tel. +48-501-510-524



VMP Group sp. z o.o. | ul.  Zawiła 65E | 30-390 Kraków

NIP: 6762580246 | KRS: 0000839593

________________________________
Od: PauloHomey ***@***.***>
Wysłane: Sunday, July 14, 2024 12:25:01 PM
Do: Piotr-Grochowski/eu.blebox ***@***.***>
DW: Piotr Grochowski ***@***.***>; Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Hi Piotr.

Something new for me about rain sensor? Status still the same: Water alarm signalizing during the powered sensor in the office on the table ;).
Thx a lot.

**Comment by Piotr-Grochowski** [comment]
One more thing - please try restarting BleBox app. Maybe it will help temporarily.


Pozdrawiam,

Piotr Grochowski

www.vmp.com.pl<http://www.vmp.com.pl/> | ***@***.******@***.***> | tel. +48-501-510-524



VMP Group sp. z o.o. | ul.  Zawiła 65E | 30-390 Kraków

NIP: 6762580246 | KRS: 0000839593

________________________________
Od: PauloHomey ***@***.***>
Wysłane: Friday, July 12, 2024 6:33:54 PM
Do: Piotr-Grochowski/eu.blebox ***@***.***>
DW: Piotr Grochowski ***@***.***>; Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Hi Pioter.

Now is it permanently displaying YES Water Alarm, and only red flashing this icon. No more changing from No to Yes. Piotr what is the sense of this warning? When should be triggered this warning? In case of the starting rain and stopped when is rain over? Because the sensor was no more 4 days outdoor, was in the room.
Thx.
Robert

**Comment by PauloHomey** [comment]
Hi Piotr. 
Have a nice vacation👍🏻😉. Of course, understood. 
BleBox app for Homey altready restarted. Nothing helps - I am one step back as I did this restart: Now is no more only changing the active alarm between red-normal-red, but changing between No alarm- Yes alarm again. 
Thx. 
How told, slowly vacation 😉👍🏻

**Comment by PauloHomey** [comment]
Video

https://github.com/user-attachments/assets/c9980ace-d70e-4c58-ac2f-7643db74c89e

**Comment by Piotr-Grochowski** [comment]
Hello,
I think you have a new firmware version of rainSensor, which was not properly supported by BleBox App. I’ve made a quick bugfix.
Please try installing test version of the app: https://homey.app/pl-pl/app/eu.blebox/BleBox/test/
Then let me know if it’s ok – I’ll push it then to production.

Pozdrawiam,
Piotr Grochowski
www.vmp.com.pl<http://www.vmp.com.pl/> | ***@***.******@***.***> | tel. +48-501-510-524

VMP Group sp. z o.o. | ul.  Zawiła 65E | 30-390 Kraków
NIP: 6762580246 | KRS: 0000839593


Od: PauloHomey ***@***.***>
Odpowiedź do: "Piotr-Grochowski/eu.blebox" ***@***.***>
Data: poniedziałek, 15 lipca 2024 o 21:49
Do: "Piotr-Grochowski/eu.blebox" ***@***.***>
DW: Piotr Grochowski ***@***.***>, Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Hi Piotr.
Have a nice vacation👍🏻😉. Of course, understood.
BleBox app for Homey altready restarted. Nothing helps - I am one step back as I did this restart: Now is no more only changing the active alarm between red-normal-red, but changing between No alarm- Yes alarm again.
Thx.
How told, slowly vacation 😉👍🏻

**Comment by nascasebastian** [comment]
Dear Piotr-Grochowski, can you please help me to integrate the BleBox SensorTemp in Homey? 
c54b739f-616c-4d68-af37-8174e2677358
![BleBox](https://github.com/user-attachments/assets/d59e48c7-7fc6-4552-9e82-8c3a12749901)
![Homey_1](https://github.com/user-attachments/assets/b54348dc-634d-4d70-a698-d40961f00ecf)
![Homey_2](https://github.com/user-attachments/assets/a8fd55f7-f2c1-4e5c-8073-60fa6201c7bf)

Thank You

**Comment by Piotr-Grochowski** [comment]
Hello,
What is the exact problem you have?

In the diagnostic report I can see the following error:

Error: connect EHOSTUNREACH 192.168.1.14:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.14',
  port: 80
}

It means that 192.168.1.14 is not reachable (network problem). Is it your tempSensor?

Pozdrawiam,
Piotr Grochowski
www.vmp.com.pl<http://www.vmp.com.pl/> | ***@***.******@***.***> | tel. +48-501-510-524

VMP Group sp. z o.o. | ul.  Zawiła 65E | 30-390 Kraków
NIP: 6762580246 | KRS: 0000839593


Od: nascasebastian ***@***.***>
Odpowiedź do: "Piotr-Grochowski/eu.blebox" ***@***.***>
Data: wtorek, 13 sierpnia 2024 o 09:58
Do: "Piotr-Grochowski/eu.blebox" ***@***.***>
DW: Piotr Grochowski ***@***.***>, Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Dear Piotr-Grochowski, can you please help me to integrate the BleBox SensorTemp in Homey?
c54b739f-616c-4d68-af37-8174e2677358
BleBox.JPG (view on web)<https://github.com/user-attachments/assets/d59e48c7-7fc6-4552-9e82-8c3a12749901>
Homey_1.JPG (view on web)<https://github.com/user-attachments/assets/b54348dc-634d-4d70-a698-d40961f00ecf>
Homey_2.JPG (view on web)<https://github.com/user-attachments/assets/a8fd55f7-f2c1-4e5c-8073-60fa6201c7bf>

Thank You

**Comment by nascasebastian** [comment]
![Yes](https://github.com/user-attachments/assets/aeb231ef-f6b2-41e7-bf65-238008a5b230)

**Comment by nascasebastian** [comment]
Yes, it`s connected. Please ask if you need more details :)

**Comment by Piotr-Grochowski** [comment]
Hello,
You’ve got a new version of the tempSensor – v2 – which is not supported by the production version of the BleBox App yet.
BUT I’ve added the support to the next test version – please install and check it out from here: https://homey.app/pl-pl/app/eu.blebox/BleBox/test/
Let me know if it works for you.

Pozdrawiam,
Piotr Grochowski
www.vmp.com.pl<http://www.vmp.com.pl/> | ***@***.******@***.***> | tel. +48-501-510-524

VMP Group sp. z o.o. | ul.  Zawiła 65E | 30-390 Kraków
NIP: 6762580246 | KRS: 0000839593


Od: nascasebastian ***@***.***>
Odpowiedź do: "Piotr-Grochowski/eu.blebox" ***@***.***>
Data: wtorek, 13 sierpnia 2024 o 10:23
Do: "Piotr-Grochowski/eu.blebox" ***@***.***>
DW: Piotr Grochowski ***@***.***>, Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Yes, it`s connected. Please ask if you need more details :)

**Comment by nascasebastian** [comment]
Dear Piotr, 
Please find below the Screenshot :)
![Uploading BleBox_API.JPG…]()

**Comment by nascasebastian** [comment]
![BleBox_API](https://github.com/user-attachments/assets/99be0560-c028-48f3-a4ab-b8622f9ac638)

**Comment by nascasebastian** [comment]
Dear Piotr, still not working. I really  appreciate your support and fast reply :)
![NOK](https://github.com/user-attachments/assets/f123b83e-c9f8-4397-a165-8ad062c3e443)

**Comment by Piotr-Grochowski** [comment]
Please try restarting your Homey – mDNS sometimes takes time to propagate to Homey and it’s faster to restart it.
Also plese ensure that:

  *   You have a static IP set for your tempSensor in your DHCP server (on your router)
  *   You have the newest firmware of the tempSensor
  *   mDNS-SD is enabled in you network

If it doesn’t work after restart/around 30 minutes please get back to me.

Pozdrawiam,
Piotr Grochowski
www.vmp.com.pl<http://www.vmp.com.pl/> | ***@***.******@***.***> | tel. +48-501-510-524

VMP Group sp. z o.o. | ul.  Zawiła 65E | 30-390 Kraków
NIP: 6762580246 | KRS: 0000839593


Od: nascasebastian ***@***.***>
Odpowiedź do: "Piotr-Grochowski/eu.blebox" ***@***.***>
Data: wtorek, 13 sierpnia 2024 o 12:26
Do: "Piotr-Grochowski/eu.blebox" ***@***.***>
DW: Piotr Grochowski ***@***.***>, Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Dear Piotr, still not working. I really appreciate your support and fast reply :)
NOK.JPG (view on web)<https://github.com/user-attachments/assets/f123b83e-c9f8-4397-a165-8ad062c3e443>

**Comment by Piotr-Grochowski** [comment]
There is no error in the diagnostic report. So Homey just does not see your tempSensor.

Please send me the results of the URLs:
http://IP/info
http://IP/state
where IP is your tempSensor IP address. Just put those URLs in your webbrowser and let me know what does it give you (copy-paste).

Pozdrawiam,
Piotr Grochowski
www.vmp.com.pl<http://www.vmp.com.pl/> | ***@***.******@***.***> | tel. +48-501-510-524

VMP Group sp. z o.o. | ul.  Zawiła 65E | 30-390 Kraków
NIP: 6762580246 | KRS: 0000839593


Od: nascasebastian ***@***.***>
Odpowiedź do: "Piotr-Grochowski/eu.blebox" ***@***.***>
Data: wtorek, 13 sierpnia 2024 o 12:48
Do: "Piotr-Grochowski/eu.blebox" ***@***.***>
DW: Piotr Grochowski ***@***.***>, Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Dear Piotr, I own Unifi UDM networking equip. Everywhere mDNS and Snooping is enabled. I set IP Static for the BleBox Temp Sensor and I restarted. Same situation. See please the Diagnostic 491c6694-ad36-4e04-9d1e-898697d284a5

**Comment by nascasebastian** [comment]
Hmm, thats strange...
http://IP/info
{"device":{"deviceName":"POOL TEMPERATURE","type":"tempSensor","product":"tempSensor_v2","hv":"tS-2.0","fv":"0.1028","universe":0,"apiLevel":"20220501","iconSet":63,"categories":[4,7],"id":"0af9e0712a07","ip":"192.168.1.14","availableFv":null}}

http://IP/state
{"tempSensor":{"sensors":[{"type":"temperature","id":0,"value":2931,"trend":1,"state":2,"elapsedTimeS":1}]}}

**Comment by Piotr-Grochowski** [comment]
OK, I think now I see what the issue is with tempSensor v2. I assumed it uses new API too, but it still uses old one. Please check the new test version.

Pozdrawiam,
Piotr Grochowski
www.vmp.com.pl<http://www.vmp.com.pl/> | ***@***.******@***.***> | tel. +48-501-510-524

VMP Group sp. z o.o. | ul.  Zawiła 65E | 30-390 Kraków
NIP: 6762580246 | KRS: 0000839593


Od: nascasebastian ***@***.***>
Odpowiedź do: "Piotr-Grochowski/eu.blebox" ***@***.***>
Data: wtorek, 13 sierpnia 2024 o 12:59
Do: "Piotr-Grochowski/eu.blebox" ***@***.***>
DW: Piotr Grochowski ***@***.***>, Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Adding of the rainsensor to Homey (Issue #13)


Hmm, thats strange...
http://IP/info
{"device":{"deviceName":"POOL TEMPERATURE","type":"tempSensor","product":"tempSensor_v2","hv":"tS-2.0","fv":"0.1028","universe":0,"apiLevel":"20220501","iconSet":63,"categories":[4,7],"id":"0af9e0712a07","ip":"192.168.1.14","availableFv":null}}

http://IP/state
{"tempSensor":{"sensors":[{"type":"temperature","id":0,"value":2931,"trend":1,"state":2,"elapsedTimeS":1}]}}

**Comment by Piotr-Grochowski** [comment]
Not at the moment, but thanks.
Please try new 3.14.7

**Comment by nascasebastian** [comment]
Hello Piotr, Hopping I will not screw your today Good Mood, but still not working :)

**Comment by nascasebastian** [comment]
Hello Dear Piotr, do you have any updates?

**Comment by Piotr-Grochowski** [comment]
Hello, I believe it's something wrong with your mDNS configuration in your LAN. I just connected my test tempSensor to the network and Homey found it without a problem.

![IMG_1549](https://github.com/user-attachments/assets/4bb48ccf-193b-47de-b1f8-a0e7a220dfec)

So please download any freeware software for you computer or mobile to check which mDNS services are available.

**Comment by nascasebastian** [comment]
![Piotr](https://github.com/user-attachments/assets/109754ce-4233-435c-a84e-b619ad068ae8)
Should be enabled according to the actual settings

**Comment by Piotr-Grochowski** [comment]
I don't know your router, so I don't think I'll be able to help you with that. Try turning off IGMP snooping, maybe it will help. But rather test, if it works, or not by using any mDNS client on your PC or mobile - connected to the same WiFi Access Point or via Ethernet cable - as your Homey is. So you would simulate homey accessing mDNS in your network.

**Comment by nascasebastian** [comment]
![POOL](https://github.com/user-attachments/assets/65255310-8178-4d12-a9a7-3377f90c2466)
Goodddd Work Piotr! With the Test version works now! :) Better later than never :)

**Comment by Piotr-Grochowski** [comment]
So what was the final problem? The IGMP setting on the router or something different?

**Comment by nascasebastian** [comment]
![POOL](https://github.com/user-attachments/assets/2f45c54c-bbfd-40ce-b5cb-12da33dbd3e2)

I added the Default and Backup in in IoT Auto-Discovery list and I disabled the IGMP.

**Comment by Piotr-Grochowski** [comment]
OK, great.
