### ISSUE TITLE
po aktualizacji 3.14.2 problemy

### ISSUE THREAD

**Issue by Rolandr23** [Piotr-Grochowski/eu.blebox#14]
witam
urzadzenie niedostępne w homey pro 2019, wapk ble działa i ma status
mimio powrotu do 3.14.1, dale nie działa w homey
nie pomagaja restarty apk, o odłączenie od zasilania również

**Comment by Rolandr23** [comment]
zaczeło działać po 20minutach na nowej wersji z powrotem

**Comment by Piotr-Grochowski** [comment]
Nie za bardzo zrozumiałem, co nie działało i czy finalnie działa i problemu nie ma?

**Comment by Rolandr23** [comment]
Już jest ok, dzięki
