### ISSUE TITLE
Cannot find Airsensor

### ISSUE THREAD

**Issue by eddiegonzales** [Piotr-Grochowski/eu.blebox#15]
Hi,

I have changed my wireless configuration. And even though i connected the airsensor to the new wifi without any issues, my Homey Pro app did not update anymore. Then i deleted the device in homey and when i try to add it again, it says it cannot find any new devices. I have even tried to delete the app and installed it again without any help. I know its ip but i cannot add it manually because there is no options to do this.

**Comment by eddiegonzales** [comment]
Today it worked by adding the sensor in a browser window instead of the app on the iphone. Closing issue again

**Comment by Piotr-Grochowski** [comment]
Searching for devices via mDNS-SD is done by Homey itself, not the website of the mobile App. So if you could connect it means Homey found your device and it should show up no matter which app (web or mobile) you use. Not always the devices show in the discovery window after installing them. On some installs (I don’t know what is the exact reason, it might depend on your network config), they start to show up in a few minutes or even hours….
