### ISSUE TITLE
App doesn't work anymore

### ISSUE THREAD

**Issue by malekim** [Piotr-Grochowski/eu.blebox#16]
Today, the app uninstalled itself and won't reinstall. I'm using Homey Pro 2023, version 12.02.2.

**Comment by Piotr-Grochowski** [comment]
What do you mean by writing „the app uninstalled itself”? How can app do it without your action? What is happening if you try to install it?

**Comment by malekim** [comment]
That's a good question. 

The app just disappeared from the apps. The accessory wasn't working and there was a notification that the BleBox app is not installed. When I tried to install the app again, it hadn't been installing, but without any error. 

Also, the accessory was working fine in the official BleBox iOS app.

**Comment by malekim** [comment]
I've got only two apps installed, so it's not the problem. Next time when it happens, I will try to check through SSH what's going on.
