### ISSUE TITLE
Temp sensor adding problem

### ISSUE THREAD

**Issue by PatrikMihalik** [Piotr-Grochowski/eu.blebox#17]
Hello Piotr

I have a litle problem with temp sensor V2.
I add this device to wbox app. But it is not possible add device to homey. Homey dont see it.
No new device found. 

Can you help me with it.

Thank you.
Patrik

**Comment by PatrikMihalik** [comment]
Sorry I have collision in IP adress

**Comment by PatrikMihalik** [comment]
Hello Piotr,

There is some possibility to have the same name for each temperature from original wbox app in homey too?

It is just a question? 

🙂

**Comment by Piotr-Grochowski** [comment]
Hello,
When you connect Homey to you BleBox device for the first time, the name is taken as it is in the device/wBox app. But it's not synchronized later.

**Comment by PatrikMihalik** [comment]
Thank you Piotr,

I have just last question,there is any possibility to change name directly in advanced setting in homey for.each temperature?

**Comment by Piotr-Grochowski** [comment]
No, advanced settings are only for changing IP and polling.
