### ISSUE TITLE
raisensor Blebox

### ISSUE THREAD

**Issue by Rolandr23** [Piotr-Grochowski/eu.blebox#2]
Mam Homey pro v 2021, interesuje mnie blebox rain sensor, czy jest wymagana jakas bramka do tego czujnika, zasilacz?
Czy sama instalacja aplikacji ble box, czy nawet nie trzeba instalować i jest widoczna po podłączeniu do zasilacza w Homey pro?

**Comment by Piotr-Grochowski** [comment]
Witam,
rainSensor to urządzenie zasilane prądem stałym 12-24V, więc wymaga zasilacza - np. takiego jak do LEDów. 
Można też wykorzystać dodatkowo rain&windSensor, do którego podpina się rainSensor (a w przyszłości także wiatraczek z windSensor jak zostanie wydany) - ta kostka zasilana jest już 230V, więc nie potrzeba dodatkowego zasilacza.

Odnośnie bramki - nic nie trzeba, to jest urządzanie WiFi.

Instalacja - najłatwiej poprzez aplikację wBox, ale nie jest ona konieczna. Można to samo zrobić przeglądarką internetową - wystarczy podłączyć się telefonem/tabletem/laptopem do sieci WiFi, którą emituje nowa, nieskonfigurowana kostka, następnie przeglądarką podłączyć się na adres kostki - i tu można ją skonfigurować tak, jak poprzez aplikację wBox. Ja mimo wszystko wykorzystuję aplikację, bo jest po prostu wygodniej. Instalacja polega przede wszystkim na dołączeniu kostki do domowej sieci WiFi, to jest konieczne, aby Homey mógł ją normalnie widzieć. Można tez poustawiać trochę różnych innych rzeczy, zaktualizować firmware, etc.

**Comment by Rolandr23** [comment]
dziękuję za wyczerpującą odpowiedz, o to mi chodziło :)

**Comment by Piotr-Grochowski** [comment]
Wydaje mi się, że powinien być OK - jest 12V i ma dużą moc (rainSensor zjada duuużo mniej), aczkolwiek musisz tutaj odciąć wtyczkę (chyba, że do rainSensora dorobisz gniazdko), więc stracisz gwarancję. Ja do akcesoriów zewnętrznych (np. do airSensora) stosuję taki: https://allegro.pl/oferta/zasilacz-12v-30w-ip67-do-tasma-led-rgb-dopuszkowy-13094443311 -> jest mały i można go schować łatwo w puszce, sama konstrukcja zasilacza jest wodoszczelna, co w przypadku akcesoriów zewnętrznych jest mocno wskazane :)

**Comment by Piotr-Grochowski** [comment]
Wróććć, ten co podałem do rainSesora się nie nada, bo ma 2W, a rainSensor wymaga min 6W.

**Comment by Piotr-Grochowski** [comment]
Tu jest wodoszczelny o większej mocy: https://allegro.pl/oferta/zasilacz-12v-led-15w-hermetyczny-wodoszczelny-ip67-12821276563
W puszce standardowej się nie zmieści, ale można zrobić inną natynkową o większym wymiarze.

**Comment by Rolandr23** [comment]
ten co podałes link

**Comment by Rolandr23** [comment]
przyszedł, podłączyłem zainstalowałem w apce blebox, jednak nie widzę go w homey. Cos jeszcze musze zrobić?

**Comment by Piotr-Grochowski** [comment]
Może nie jest zaktualizowany do najnowszej wersji firmware? Odpalasz bezpośrednio z zasilaczem, czy poprzez rain&windSensor?
Odpal w przeglądarce http://IP/api/device/state
zmieniając tekst "IP" na adres IP rainSensora i podeślij wynik.

**Comment by Rolandr23** [comment]
oprogramowanie aktualne, nawet wgrałem na homey testowa wersję i nic
{"device":{"deviceName":"My rainSensor","type":"multiSensor","product":"rainSensor","hv":"rs.2.0","fv":"0.1023","universe":0,"apiLevel":"20200831","categories":[4],"id":"4a3fdaadb0a0","ip":"192.168.1.121","availableFv":null}}

**Comment by Piotr-Grochowski** [comment]
Czy masz jakiegokolwiek innego BleBoxa spiętego z Homey, czy to Twój jedyny? Objaw wygląda mi na typowy, gdy router wycina ruch mDNS-SD (wykrywanie urządzeń protokołem multicastowym). Jaki masz model routera?

**Comment by Rolandr23** [comment]
jedyny blebox, router czy ap ?

**Comment by Piotr-Grochowski** [comment]
To może opisz dokładniej swoją infrastrukturę, bo widzę, jest bardziej złożona :)

**Comment by Rolandr23** [comment]
Router na strychu do którego podpiety jest ap tl-wa1201 na dole

**Comment by Rolandr23** [comment]
coś zrobiłeś? bo przed chwilą mi się dodał :)

**Comment by Piotr-Grochowski** [comment]
Nic nie robiłem, starałem się odnaleźć instrukcję od tego Xiaomi, ale nie mogę nic od niego znaleźć.

Skoro zaczął działać to OK, ale obserwuj w takim razie stabilność. Może problem z zasięgiem (mDNS wymaga stabilnego połączenia)?

**Comment by Rolandr23** [comment]
nie pada 0mm pada 1mm?

**Comment by Rolandr23** [comment]
nie ma historii w homey, tylko flow gdy kliknie sie w ikonkę?

**Comment by Piotr-Grochowski** [comment]
Pytasz o historię opadów? Powinna być w insights.

**Comment by Rolandr23** [comment]
szkoda, mam tyle urządzeń zanim to znajdę w insights  :( , była by to przydatna funkcja

**Comment by Piotr-Grochowski** [comment]
Nie spotkałem się z sensorem, który miałby historię odczytów "na sobie" - tylko w insights. W historii pojawiają się chyba tylko zapisy z urządzeń wykonawczych (np. włączono przycisk, wyłączono przycisk) oraz alarmy, i de facto jako twórca aplikacji nie mam wpływu, co w historii się wpisuje - to autogeneruje Homey dla odpowiednich typów "capabilities" (albo tego nie odkryłem - taka możliwość też jest).

Odnośnie migania na czerwono - czyli utworzenia customowego alarmu wystąpienia deszczu - to mógłbym zrobić. Czy masz ten netatmo lub jakiegoś screena jak to wygląda tam?

**Comment by Rolandr23** [comment]
rozumiem, nie posiadam netatmo ale fajnie wygląda po kliknieciu na ikonkę taki właśnie alarm "w środku", tak jak jest np. w czujniku zalania czy w czujniku nawet ruchu ikonka w środku miga na czerwono, tez dodatkowa możliwość zamiast na głównej ikonce zamiast 1mm ten wykrzyknik zółty, możliwość zmiany albo też inna ikonka np. parasola tez była by wskazana
![Bez tytułu 2](https://user-images.githubusercontent.com/125920117/221011785-b7d0c3ad-66c5-438f-b624-e68ff84ed38a.png)
![Bez tytułu](https://user-images.githubusercontent.com/125920117/221011787-3f3f84fe-17c4-4586-9e79-0e22513d389c.png)

**Comment by Rolandr23** [comment]
w czujniku zalania aqary który przerabiałem na czujnik deszczu ta kto wygląda, łezka gdy padał deszcz migała na czerwono
![cz](https://user-images.githubusercontent.com/125920117/221012676-7cafd09b-cc16-4bad-b393-3ac94fee4511.png)

**Comment by Piotr-Grochowski** [comment]
No tak, bo to czujnik zalania i w Homey istnieje capability "alarm zalania", natomiast nie chciałbym go stosować dla deszczu, bo to jednak coś innego. Alarm zalania, alarm z czujki ruchu, alarm otwarcia drzwi itp. jest po prostu wykorzystywany w systemach alarmowych/antywłamaniowych (w Homey jest też apka do tego, wykorzystująca te alarmy), natomiast deszcz to trochę inny case. Ale postaram się utworzyć customowy alarm odnośnie deszczu, aby można było mieć tego typu funkcjonalność - jednak proszę o cierpliwość, mam kilka innych rzeczy o wyższym priorytecie teraz w apce. :)

**Comment by Rolandr23** [comment]
dziękuję bardzo, miłego dnia

**Comment by Rolandr23** [comment]
witaj, ponownie podłączyłem go w prawie docelowe miejsce na zewnątrz, od ap jakieś 4-5 metrów za scianą z pustaka
homey go nie widzi, 
widoczny na pingi w apce blebox widoczny a tu taki zonk. 
gdy przejdę do środka domu do 10 minut jest widoczny
co robić?
skoro nie działa w swoim miejscu z homeyem będę musiał go zwrócić

**Comment by Piotr-Grochowski** [comment]
Daj proszę screen z pinga.

Pozdrawiam,
Piotr Grochowski
________________________________
Od: Rolandr23 ***@***.***>
Wysłane: Friday, February 24, 2023 6:41:31 PM
Do: Piotr-Grochowski/eu.blebox ***@***.***>
DW: Piotr Grochowski ***@***.***>; State change ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] raisensor Blebox (Issue #2)


witaj, ponownie podłączyłem go w prawie docelowe miejsce na zewnątrz, od ap jakieś 4-5 metrów za scianą z pustaka
homey go nie widzi,
widoczny na pingi w apce blebox widoczny a tu taki zonk.
gdy przejdę do środka domu do 10 minut jest widoczny
co robić?
skoro nie działa w swoim miejscu z homeyem będę musiał go zwrócić

**Comment by Rolandr23** [comment]
![image](https://user-images.githubusercontent.com/125920117/221276168-960f3b01-3324-4497-8936-d87c2228d0a8.png)

**Comment by Rolandr23** [comment]
wcześniej restrartowałem apkę i czekałem ponad 30 minut i nic, teraz patrzę i pokazuje że 1 w homey i urzadzenie jest, 0 w ble box, zrestartowałem apke i wygląda na to że działa, po jakim czasie jest reconect od wyłaczenia albo utraty netu? strasznie to opornie nawiązuje z homey połączenie, z bleboxem w którym działa od razu i jest widoczne. Pigni chodzą zawsze przy właczonym urzadzeniu bez problemu stabilnie. Raz wyłączyłem go zasilania na 2 s. 3 metry od AP w domu 
i nie stracił połaczenia

**Comment by Piotr-Grochowski** [comment]
Tak, jak pisałem - pokaz proszę wynik z pinga.

Pozdrawiam,
Piotr Grochowski
________________________________
Od: Rolandr23 ***@***.***>
Wysłane: Friday, February 24, 2023 8:59:36 PM
Do: Piotr-Grochowski/eu.blebox ***@***.***>
DW: Piotr Grochowski ***@***.***>; State change ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] raisensor Blebox (Issue #2)


wcześniej restrartowałem apkę i czekałem ponad 30 minut i nic, teraz patrzę i pokazuje że 1 w homey i urzadzenie jest, 0 w ble box, zrestartowałem apke i wygląda na to że działa, po jakim czasie jest reconect od wyłaczenia albo utraty netu? strasznie to opornie nawiązuje z homey połączenie, z bleboxem w którym działa od razu i jest widoczne. Pigni chodzą zawsze przy właczonym urzadzeniu bez problemu stabilnie. Raz wyłączyłem go zasilania na 2 s. 3 metry od AP w domu
i nie stracił połaczenia

**Comment by Piotr-Grochowski** [comment]
Ok, teraz widzę. I to jest ping gdy jest na zewnątrz?

Pozdrawiam,
Piotr Grochowski
________________________________
Od: Rolandr23 ***@***.***>
Wysłane: Friday, February 24, 2023 8:44:49 PM
Do: Piotr-Grochowski/eu.blebox ***@***.***>
DW: Piotr Grochowski ***@***.***>; State change ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] raisensor Blebox (Issue #2)


[image]<https://user-images.githubusercontent.com/125920117/221276168-960f3b01-3324-4497-8936-d87c2228d0a8.png>

**Comment by Rolandr23** [comment]
tak, gdy jest na zewnątrz

**Comment by Rolandr23** [comment]
ruszysz go 30 cm i gubi połączenie i nie wiadomo kiedy nawiąże, ustawiłem go 10 cm od docelowego miejsca sprawdziłem aby był najlepszy ping od 4 do 6 ms na razie jest niedostepny homey, czekam

**Comment by Rolandr23** [comment]
tam gdzie wchodzi kabel wydaje sie być lekko nie szczelny, zastanawiam sie nad silikonem :) ale to po tych testach z połączeniem

**Comment by Piotr-Grochowski** [comment]
Telefon masz z Androidem czy iOS? Kiedyś dostałem link do apki od producenta do testowania mDNS - dzięki niej wyszło mi ze problemem był router, ale ona jest tylko na Android.

Pozdrawiam,
Piotr Grochowski
________________________________
Od: Rolandr23 ***@***.***>
Wysłane: Saturday, February 25, 2023 9:00:02 AM
Do: Piotr-Grochowski/eu.blebox ***@***.***>
DW: Piotr Grochowski ***@***.***>; State change ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] raisensor Blebox (Issue #2)


ruszysz go 30 cm i gubi połączenie i nie wiadomo kiedy nawiąże, ustawiłem go 10 cm od docelowego miejsca sprawdziłem aby był najlepszy ping od 4 do 6 ms na razie jest niedostepny homey, czekam

**Comment by Rolandr23** [comment]
Zamontowałem na stałe , po godzinie sie pojawił w homey heheheh, zainstalowałem tez skill na aleksie bo mi wpadło do głowy aby tam to jeszcze powiązać ale aleksa go nie znajduje choć jest skill. Telefon w Androidzie, Nie bede przeciez zmieniał routera dla czujnika deszczu, tym bardziej, że ten router to petarda stabilności :) za rozsądną cenę, poza tym wiesz mam na prawdę dużo urządzeń i wszystko się łączy idealnie. Ta płytka się nagrzewa kiedy? gdy śnieg zalega na czujniku? Pozostałe czujniki bleboxa wykorzystują podobne połączenie do homey? Czy gdy kupie inny czujnik bleboxa np. switch będzie się pewnie łączył podobnie ? Mam na myśli szybkość :). Bo mam sprytny plan gdyby były problemy z tym sensorem :) Skoro działa w apce bez problemu może wysyłać info do switcha

**Comment by Rolandr23** [comment]
aaa i jeszcze jedno położenie tego czujnika ma być w poziomie? lekko go pochyliłem 

![image](https://user-images.githubusercontent.com/125920117/221359536-4175fcf1-4a9b-4aea-94b3-333979d73e38.png)

**Comment by Piotr-Grochowski** [comment]
Tzn. powiem szczerze, że nie mam problemów, ani za bardzo zgłoszeń o problemach ze stabilnością połączenia - za wyjątkiem sytuacji, gdy jest rzeczywiście problem z WiFi (najczęściej niestety na routerach/ap TPLink). Homey zarządza wyszukiwaniem według protokołu mDNS-SD (nie mam na niego wpływu), nie wiem z jaką częstotliwością odpytuje o dostępność urządzenia. Na pewno w momencie dodawania nowego urządzenia - od razu - ale, gdy urządzenie jest już w systemie i stanie się niedostępne - nie wiem po jakim czasie idzie ponowne odpytanie o dostępność.

Testować można na Androidzie aplikacją "service browser". Odpytując domenę ".local" powinno zwrócić _bbxsrv._tcp. z ilością znalezionych serwisów - można podejrzeć, jakie są dostępne. W ten sposób działa zarówno cały BleBox (poza najstarszymi - te dodaje się ręcznie wskazując ich IP) jak i sporo innych urządzeń.

Odnośnie pytań o podgrzewanie, kąt nachylenia, etc - nie wiem, tutaj trzeba by zapytać producenta. Najprościej na grupie użytkowników BleBox na FB.
