### ISSUE TITLE
Homey couldn't find temp sensors

### ISSUE THREAD

**Issue by Janemann183** [Piotr-Grochowski/eu.blebox#5]
Since last update of Homey my temp sensor where disconnected. Reinstalling the blebox app wouldn't have any effect.
wBox app on android phone shows sensor correct 
![Screenshot_20230413-104440](https://user-images.githubusercontent.com/130649401/231706804-7ea1529e-deac-4da3-a352-2fe9f85b6f18.png)

**Comment by Piotr-Grochowski** [comment]
Hello, 
The diagnostic report does not show any errors. Please try restarting Homey. A few users reported that they've had similar problems with finding new devices with MDNS-SD and after Homey restart it started working again.

**Comment by Janemann183** [comment]
Thanks for your reply. Also after restarting homey no device is shown.

**Comment by Piotr-Grochowski** [comment]
Is tempSensor the only BleBox device you've got or do you have more of them? I have no other reports from users regarding tempSensor and it's the most popular BleBox device used with Homey...
In most cases such problems are connected with router blocking some traffic. Communication with Homey and discovery of BleBox device is based on mDNS-SD protocol, which may be blocked by some routers. Could you check your configuration if mDNS-SD is allowed in your network?
