### ISSUE TITLE
Ble box range and freezing app

### ISSUE THREAD

**Issue by PatrikMihalik** [Piotr-Grochowski/eu.blebox#7]
Hello Piotr.

i contact you with problem stop working or freezing the app,ble box shows 75degree but homey apps freeze on 48 apx las update 14h ago. After restart app everything working again but now I didnt restart  app due the report for you.

26fab464-21d3-42fa-a11b-9af8076db802

Second thing is range in flow.
There is no possibility gange temperature,there is a range max min nothing between.Better will be label with set the number. NOW i use yout experimental app.

Please look on it,thank you Piotr.

**Comment by Piotr-Grochowski** [comment]
Hello,
I analyzed the log. It looks like the connection between the Homey and the BleBox device hangs:

Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at Socket.socketOnEnd (node:_http_client:466:23)
    at Socket.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET'
}

I don't know yet what is the reason (maybe the connection between the devices is slow?) and I don't know why after the connection hungs, the Homey does not try to reconnect once again. What is the polling interval set for this device?

**Comment by PatrikMihalik** [comment]
Hello Piotr,
Connection between blebox and homey or router must be OK there is just one small wall and short distance. Pooling interval was 5000ms now I change to 10000ms and we will see.

 To the range button,it is problem for mobile app in PC version everything working. Maybe upgrade problem :-(
 
 Patrik

**Comment by Piotr-Grochowski** [comment]
5000ms is a long interval, so it shouldn't be the case, I don't think that raising to 10000ms will solve it. I'll try to dig into this problem. Unfortunately you're the only one with it, so it is of "weird" category and may be hard to investigate.

Reg. the mobile app vs PC - please send me the screenshots, maybe I am able to force it to work properly.

**Comment by PatrikMihalik** [comment]
This is screen from PC app,there is possible to change temperature by the range slider,but is not possible write exact number.

![image](https://github.com/Piotr-Grochowski/eu.blebox/assets/129721129/a06575ad-b340-4e83-be46-23e3995e9a82)

With mobile apps is not possible to move with slider,it jump to diff. values and is not possible to write exact number too.

![image](https://github.com/Piotr-Grochowski/eu.blebox/assets/129721129/9fafe3c1-7434-4903-a455-867feb267dfd)

I trying to link the video:

https://photos.app.goo.gl/iqbMvgkgTN3tS66P6

**Comment by PatrikMihalik** [comment]
Hello Piotr anything new in this case? Today ble box freeze again. ☹️

**Comment by Piotr-Grochowski** [comment]
Hello,
No, not yet. Quick workaround I can think of if it happens once a few days - prepare a flow which restarts BleBox app everyday e.g. in the night - at 3am.

**Comment by PatrikMihalik** [comment]
OkI, I understand,thank you 😉

**Comment by PatrikMihalik** [comment]
Hello Piotr,your recommandation restart ble box every day in the morning working.But today I realize that information between blebox and homey stop working. Ble-box works but in HOMEY I see data from night. After manual restart still same problem,after few restarts same problem.It start working just after hard reset the ble-box with SWITCH ON/OFF circuit breaker. :-(

**Comment by Piotr-Grochowski** [comment]
A few other persons have similar problems with other blebox devises. It looks like blebox devices hang when they have weak WiFi connection and after several failures they hang and only resetting of the circuit breaker helps.
I’m reporting this to the BleBox company, maybe they will be able to help with the issue.

Pozdrawiam,
Piotr Grochowski
www.vmp.com.pl<http://www.vmp.com.pl/> | ***@***.******@***.***> | tel. +48-501-510-524

VMP Group sp. z o.o. | ul.  Zawiła 65E | 30-390 Kraków
NIP: 6762580246 | KRS: 0000839593


Od: PatrikMihalik ***@***.***>
Odpowiedź do: "Piotr-Grochowski/eu.blebox" ***@***.***>
Data: wtorek, 25 lipca 2023 o 11:39
Do: "Piotr-Grochowski/eu.blebox" ***@***.***>
DW: Piotr Grochowski ***@***.***>, Comment ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Ble box range and freezing app (Issue #7)


Hello Piotr,your recommandation restart ble box every day in the morning working.But today I realize that information between blebox and homey stop working. Ble-box works but in HOMEY I see data from night. After manual restart still same problem,after few restarts same problem.It start working just after hard reset the ble-box with SWITCH ON/OFF circuit breaker. :-(

**Comment by PatrikMihalik** [comment]
It is good ne Piotr.
I hope that it solve my problem and everything will be work.

**Comment by Piotr-Grochowski** [comment]
Hello, one more question to you - do you have your blebox device IP set as static (DHCP in your router) or does it change?

**Comment by PatrikMihalik** [comment]
I think it is se to static. But I check it when I am at home today afternoon.
Now after homey update everything works,thermostat temperature setting is OK.
Just one think is missing and it is energy measuring,like in your previous version.

Patrik

**Comment by Piotr-Grochowski** [comment]
Yes, I will add those energy measurements soon.

**Comment by Piotr-Grochowski** [comment]
Please remove thermoBox from your Homey (unfortunately required this time), install the new test app and re-add thermoBox (only one type - just thermoBox - is available this time in the app). It should now also have the energy measurements. Please let me know if it works ok for you.

**Comment by PatrikMihalik** [comment]
Hello Piotr,

I had two devices till now. Old one with experimental apps without measuring and second one high temp from standard app.
I keep old one because I using power the hour for calculated consumption. Pls Can you create another one test app? When  I remove your experimental I remove all flows which I have now. But If it no other way I try to do some printscreens and create flows again.

thank you.

**Comment by PatrikMihalik** [comment]
Hello Piotr,

Yesterday evening I made prtscrn on my flows and removed and added new blebox device.
After readded i must repaired all flows but now everything works. :-)
Even the power consuption in app power by hour works :-)
Thank you a lot Piotr,you are great developer.


![image](https://github.com/Piotr-Grochowski/eu.blebox/assets/129721129/310bf80e-bda6-41ff-b68b-245f0ec80591)
![image](https://github.com/Piotr-Grochowski/eu.blebox/assets/129721129/1624c7ef-40aa-458c-8c24-71e18f913d0b)

Patrik

**Comment by Piotr-Grochowski** [comment]
Great! You're faster than me :) 
So your homey now works on the latest experimental version of BleBox app? Let's leave it for a couple of days and let me know if it works OK. Then I will publish it to the standard version.

**Comment by PatrikMihalik** [comment]
Ok i will test it for couple of days and send you feedback.

Thank you again for great work.

:-)

**Comment by PatrikMihalik** [comment]
Hello Piotr I find first small bug. Thermostat start shows red light status when the temperature goes below setting value and ignore hysteresis range from blebox.
I have hysteresis +-0.2degree.and how you can see on picture bellow current temperature is 0.15 below but thermostat shows on status.Energy meter works good and shows right value.

For me is not problem but for someone who have bigger hysteresis.thermostat show heating (red light) but real it is not working.
![Screenshot_2023-10-21-06-46-19-819_app homey](https://github.com/Piotr-
Grochowski/eu.blebox/assets/129721129/eebe5a67-6876-41a5-a03f-fc8f4935e437)
![Screenshot_2023-10-21-06-45-58-165_app homey](https://github.com/Piotr-Grochowski/eu.blebox/assets/129721129/3e59b4b8-f01b-4468-a446-cc8722a96780)
![Screenshot_2023-10-21-06-45-52-291_app homey](https://github.com/Piotr-Grochowski/eu.blebox/assets/129721129/c4d81cc5-724b-47d1-b24f-5b167423fcdf)

**Comment by Piotr-Grochowski** [comment]
Homey does not support hysteresis. The thermostat UI displays orange color - I think - always when the measured temperature is lower than target temperature. Also there is no capability where I could send to Homey UI current operating state of the thermoBox. So I don't have an impact on the UI behavior with the colors. But I use operating state to calculate the energy usage - that's why it calculates it properly.

**Comment by PatrikMihalik** [comment]
Hello Piotr,

Everything works great. Calculating power works also good. Just the connection to other app power by hour stop working,I must create new device and rewrite values. But now works.

Great job Piotr.
Thank you a lot.

**Comment by Piotr-Grochowski** [comment]
OK, thanks for the info!

Pozdrawiam,
Piotr Grochowski
www.vmp.com.pl<http://www.vmp.com.pl/> | ***@***.******@***.***> | tel. +48-501-510-524

VMP Group sp. z o.o. | ul.  Zawiła 65E | 30-390 Kraków
NIP: 6762580246 | KRS: 0000839593


Od: PatrikMihalik ***@***.***>
Odpowiedź do: "Piotr-Grochowski/eu.blebox" ***@***.***>
Data: wtorek, 24 października 2023 o 19:36
Do: "Piotr-Grochowski/eu.blebox" ***@***.***>
DW: Piotr Grochowski ***@***.***>, State change ***@***.***>
Temat: Re: [Piotr-Grochowski/eu.blebox] Ble box range and freezing app (Issue #7)


Hello Piotr,

Everything works great. Calculating power works also good. Just the connection to other app power by hour stop working,I must create new device and rewrite values. But now works.

Great job Piotr.
Thank you a lot.
