### ISSUE TITLE
Saunabox in homey max 35 / 40 degrees

### ISSUE THREAD

**Issue by PeterR1975** [Piotr-Grochowski/eu.blebox#8]
Hello i installed my saunabox today. 

Unfortunately, the temperature in homey can be set at a maximum of 35 degrees and in flows a maximum of 40 degrees. This is a bit low for a sauna. In the ble app i have changed the min temp to 40 and max temp to 95 degrees. Am I doing something![image](https://github.com/Piotr-Grochowski/eu.blebox/assets/71005395/2b12af6c-3c76-4ece-afc7-ed770c261b68) wrong? See picture![image](https://github.com/Piotr-Grochowski/eu.blebox/assets/71005395/befd09f9-6a0b-4ddc-8243-5a568c3314bc)

fb26b9b4-f062-4125-9b69-eacb3d5f115c

**Comment by PeterR1975** [comment]
The saunabox works just fine only the temp range in homey is max 40 degrees

**Comment by PeterR1975** [comment]
P.s ip is not 31 but 36 at the end

**Comment by Piotr-Grochowski** [comment]
Then it seems that you don't have a static IP for sainaBox set. When you added it to the Homey it was 192.168.1.31 and now it changed 192.168.1.36 - that's why BleBox app does not work properly. Please remove the saunaBox from Homey, set a static IP address in your router (DHCP) for it and then re-add to Homey. I think it should then start working properly. Also please check if saunaBox has the newest firmware installed. Please let me know if it will work now or you still have problems - then we'll investigate further (please let me know then which Homey Pro version do you have (2019 or 2023), what is the firmware version of Homey, Homey App on your mobile and saunaBox).

**Comment by PeterR1975** [comment]
Ok thanks for uour help. I did all the steps add static ip adress then removed the sauna in homey even removed your app and then reinstall it again. 
Same problem stil exist. In homey i can the max temp i can set is 35 degrees and in flows 40 degrees. 
For the rest the app works good incan also turn off and on the sauna with homey that works fine.
Let me now if you need something from me

**Comment by Piotr-Grochowski** [comment]
Please remove the saunaBox from Homey, install TEST version of the app available here: https://homey.app/en-us/app/eu.blebox/BleBox/test/ and then add saunaBox again. Please let me know if it will work now.

**Comment by PeterR1975** [comment]
Yessss! This solved all problems now i can set higher temp. Thanks for tour quick respons and help i apreciate it. ![image](https://github.com/Piotr-Grochowski/eu.blebox/assets/71005395/77bf9664-9c61-4bf4-ae20-14c6208d389c)

**Comment by Piotr-Grochowski** [comment]
That's great! If you have any other issues please let me know, for now I close this ticket. The fix will go on production (non-test) version in the next days, so for now please stay with the test version.

**Comment by PeterR1975** [comment]
Ok it was working for a day now i have problems with connection homey can not reach the saunabox. The wifi is ok see picture i can go to the saunabox interface so it is online you can see a good connection with my wifi.BLE app works normal only homey can not connect![image](https://github.com/Piotr-Grochowski/eu.blebox/assets/71005395/e08f24f7-298d-4ee9-967c-2e6f01ac7bb3)

**Comment by Piotr-Grochowski** [comment]
The error is:
Error: connect ETIMEDOUT 192.168.1.36:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.36',
  port: 80
}

So there was a timeout when trying to connect to saunaBox from Homey (In other words Homey tries to connect to saunaBox and it lasted so long that Homey thrown timeout error). So it has to be something network-related. Maybe your Homey does not have a good connection or there is a misconfiguration on the router-side?
